apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jt-xi6f-m-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:1b4801cf9627ec3caba9c8f048139c0679366f1e@sha256:e6311b0d1aac4aeca960a83fed5035525e273d05746cd5d82b5b5120c962132e
          name: container-image
